#!/bin/bash
# intialize a usb stick with a new exam set.
# this script cleans the exam user area on the usb stick.
#
# The logged in user, for who he sticks are auto mounted by udev.
me=${SUDO_USER}
debug=
if [ "root"  != "$USER" ]; then
    echo must be root or in sudo process, sorry.
    exit 1
fi
if [ ! -e skel.tgz ]; then
    echo -e "missing skel dir template 'skel.tgz';\n\t please make sure it (or a sym link) exists in the current dir."
    exit 2;
fi
# chown sandbox stuff to exam uid:gid
chown -R 1001:1001 sandbox
for i in /media/${me}/EXAM*; do 
    stick=$(basename $i)
    if [ -d sandbox/${stick} ] ; then 
    mountpoint=/media/${me}/casper-rw-${stick}
    ${debug} mkdir -p ${mountpoint}
    ${debug} mount -o loop ${i}/casper-rw  ${mountpoint}
    ( # clean exam disk, new initial and sync sandbox  
	${debug} rm -fr  ${mountpoint}/exam/exam
	${debug} tar -C ${mountpoint}/exam/ -xzf skel.tgz 
	${debug} rsync -aq --exclude .svn sandbox/${stick}/exam/exam/  ${mountpoint}/exam/exam/ 
	echo primed stick ${stick}
    ) &
    else
	echo warning: no sandbox for stick ${stick}
    fi
done
wait
sync
# unmount all
for i in /media/${me}/EXAM*; do 
    mountpoint=/media/${me}/casper-rw-$(basename ${i}) 
    ${debug} umount ${mountpoint}
    ${debug} rmdir ${mountpoint}
done
sync
for i in /media/${me}/EXAM*; do 
  ${debug}  umount ${i}
  echo unmounted  ${i}
done
